import { readFile } from "node:fs/promises";
import { builtinModules } from "node:module";
import path from "node:path";
import type { Plugin, UserConfig } from "vite";
import { defineConfig, loadEnv } from "vite";
import solidPlugin from "vite-plugin-solid";
import { viteStaticCopy } from "vite-plugin-static-copy";

const banner = `
/*!
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository https://github.com/nirtamir2/obsidian-slidev.

This bundle includes Solid (https://github.com/solidjs/solid),
Copyright (c) 2016-2025 Ryan Carniato, licensed under the MIT License:

It also includes parsing logic adapted from Slidev
(https://github.com/slidevjs/slidev),
Copyright (c) 2020-2021 Anthony Fu, licensed under the MIT License:

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

This bundle includes YAML (https://github.com/eemeli/yaml),
Copyright Eemeli Aro <eemeli@gmail.com>, licensed under the ISC License:

Permission to use, copy, modify, and/or distribute this software for any purpose
with or without fee is hereby granted, provided that the above copyright notice
and this permission notice appear in all copies.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND
FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS
OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF
THIS SOFTWARE.
*/
`;

export default defineConfig(async ({ mode }) => {
  const prod = mode === "production";

  let { OUT_DIR } = loadEnv(mode, process.cwd(), ["OUT_"]);

  OUT_DIR = path.normalize(OUT_DIR!);
  // if (OUT_DIR !== "dist" && OUT_DIR !== path.join(process.cwd(), "dist")) {
  //   await rm("dist", { recursive: true });
  //   exec(
  //     process.platform === "win32"
  //       ? `mklink /J dist ${OUT_DIR}`
  //       : `ln -s ${OUT_DIR} dist`,
  //   );
  // }

  return {
    esbuild: {
      legalComments: "inline",
    },
    plugins: [
      solidPlugin(),
      viteStaticCopy({
        targets: [
          {
            src: "manifest.json",
            dest: ".",
          },
        ],
      }),
      // prod ? undefined : inject(["./src/hmr.ts"]),
    ],
    build: {
      lib: {
        entry: "src/main.ts",
        name: "main",
        fileName: () => "main.js",
        formats: ["cjs"],
      },
      minify: prod,
      sourcemap: prod ? false : "inline",
      cssCodeSplit: false,
      emptyOutDir: true,
      outDir: OUT_DIR,
      rollupOptions: {
        output: {
          exports: "named",
          assetFileNames: (v: { name: string }) =>
            v.name === "obsidian-slidev.css" ? "styles.css" : v.name,
          banner,
        } as NonNullable<
          NonNullable<
            NonNullable<UserConfig["build"]>["rollupOptions"]
          >["output"]
        >,
        external: [
          "obsidian",
          "electron",
          "@codemirror/autocomplete",
          "@codemirror/closebrackets",
          "@codemirror/collab",
          "@codemirror/commands",
          "@codemirror/comment",
          "@codemirror/fold",
          "@codemirror/gutter",
          "@codemirror/highlight",
          "@codemirror/history",
          "@codemirror/language",
          "@codemirror/lint",
          "@codemirror/matchbrackets",
          "@codemirror/panel",
          "@codemirror/rangeset",
          "@codemirror/rectangular-selection",
          "@codemirror/search",
          "@codemirror/state",
          "@codemirror/stream-parser",
          "@codemirror/text",
          "@codemirror/tooltip",
          "@codemirror/view",
          "@lezer/common",
          "@lezer/highlight",
          "@lezer/lr",
          ...builtinModules,
          ...builtinModules.map((module) => `node:${module}`),
        ],
      },
    },
  } satisfies UserConfig;
});

// eslint-disable-next-line unused-imports/no-unused-vars, @typescript-eslint/no-unused-vars
const inject = (files: Array<string>): Plugin | null => {
  if (files.length > 0) {
    return {
      name: "inject-code",
      async load(this, id) {
        const info = this.getModuleInfo(id);
        if (info?.isEntry != null) {
          const code = await readFile(id, "utf8");
          const dir = path.dirname(id);
          const inject_code = files
            .map((v) => path.relative(dir, v))
            .map((p) => path.join("./", path.basename(p, path.extname(p))))
            .map((p) => `import './${p}'`)
            .join(";");
          return `
          ${inject_code};
          ${code}
          `;
        }
        return null;
      },
    };
  }
  return null;
};
